/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ColecaoAtualRouteImport } from './routes/colecao-atual'
import { Route as ProdutosRouteImport } from './routes/produtos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColecaoAtualRoute = ColecaoAtualRouteImport.update({
  id: '/colecao-atual',
  path: '/colecao-atual',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/colecao-atual': typeof ColecaoAtualRoute
  '/produtos': typeof ProdutosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/colecao-atual': typeof ColecaoAtualRoute
  '/produtos': typeof ProdutosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/colecao-atual': typeof ColecaoAtualRoute
  '/produtos': typeof ProdutosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/colecao-atual' | '/produtos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/colecao-atual' | '/produtos'
  id: '__root__' | '/' | '/colecao-atual' | '/produtos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColecaoAtualRoute: typeof ColecaoAtualRoute
  ProdutosRoute: typeof ProdutosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colecao-atual': {
      id: '/colecao-atual'
      path: '/colecao-atual'
      fullPath: '/colecao-atual'
      preLoaderRoute: typeof ColecaoAtualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColecaoAtualRoute: ColecaoAtualRoute,
  ProdutosRoute: ProdutosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
